### ISSUE TITLE
Something wrong happened when I use flop_regularizer on keras model.

### ISSUE THREAD

**Issue by Mintcat10** [google-research/morph-net#36]
Hi,thank you very much for open this project.
Here is my error.This is my model:
```
from keras.models import Model
from keras.layers import Dense, GlobalAveragePooling2D, Dropout

self.base_model = keras.applications.inception_v3.InceptionV3(include_top=False,weights='inception_v3_weights_tf_dim_ordering_tf_kernels_notop.h5',input_shape=input_shape)
x = self.base_model.output
x = GlobalAveragePooling2D()(x)
x = Dense(self.config.fc_size, activation='relu',)(x)
features = Dense(self.config.fc_size, activation='relu',name='features')(Dropout(self.config.dropout_ratio)(x))
predictions = Dense(1, activation='sigmoid',name='predictions')(features)
self.model = Model(input=self.base_model.input, output=[predictions,features])

network_regularizer = flop_regularizer.GammaFlopsRegularizer(
[self.model.output[0].op], gamma_threshold=1e-3)
```
When I run this ,it returns an error:
```
  File "E:\20190425_MorphNet\20190425_morph-net-master\model_local.py", line 59, in add_new_last_layer
    flop_regularizer.GammaFlopsRegularizer([self.model.output[0].op], gamma_threshold=1e-3)
  File "E:\20190425_MorphNet\20190425_morph-net-master\morph_net\network_regularizers\flop_regularizer.py", line 95, in __init__
    regularizer_blacklist=regularizer_blacklist)
  File "E:\20190425_MorphNet\20190425_morph-net-master\morph_net\framework\op_regularizer_manager.py", line 132, in __init__
    ['%s (%s)' % (o.name, o.type) for o in self._op_deque])
RuntimeError: OpRegularizerManager could not handle ops: ['dropout_1/cond/dropout/Shape (Shape)', 'dropout_2/cond/dropout/Shape (Shape)']
``` 
How could I solve this error？
And I have another question, can I use MorphNet on Keras model?

**Comment by VashishtMadhavan** [comment]
This means that your OpRegularizerManager is hitting the iteration limit (basically infinite looping) when trying to process ops in your graph. See issue #35

**Comment by ayp-google** [comment]
In this case, MorphNet is getting stuck because it doesn't know how to handle the Shape op.  You can try a couple options:
1. Try using self.base_model.output rather then the model output.  This will skip the dropout ops where the problematic Shape op is.  The dense layer is fixed size anyway so it should be fine to not regularize that layer.
2. You can try implementing an OpHandler for the Shape op or the dropout op.  The OpHandler basically tells MorphNet how the input channels and output channels are related.  For example, for the add op (e.g. c = a + b) the input channels and output channels directly map.  Removing c[0] requires removing a[0] and b[0] to keep sizes consistent.  I suspect the issue here is that the dropout op takes 2 inputs: the feature map and a noise shape tensor.  In that case, the OpHandler for dropout should only analyze the channels for the feature map and should ignore the noise shape as that has no effect on which channels are regularized together.

**Comment by Mintcat10** [comment]
Thanks a lot.I use self.base_model.output and it can work.But when I add  regularizer_loss to model_loss,train can't return correct loss.So I build a tensorflow model to use Morphnet.
