### ISSUE TITLE
Any comparisons with the tf_graph optimization approach?

### ISSUE THREAD

**Issue by MBoaretto25** [google-research/morph-net#52]
Does anyone has any results of this approach in comparison with the tensorflow graph optimization approach?

**Comment by pkch** [comment]
Which specific optimizations are you referring to? If you're talking  about freezing and rewriting the graph for inference, this is orthogonal: you still want to apply those optimizations, in addition to optimizing your channel count.

The interaction between reduced channel counts and the optimization of a graph for inference can be complex though, since the bottlenecks / critical paths in the execution may shift around as channel counts change.
